aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Models/Genre.cs
namespace ValidationSample.Models
{
    public enum Genre
    {
        Classic,
        PostClassic,
        Modern,
        PostModern,
        Contemporary,
    }
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Models/Movie.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.ComponentModel.DataAnnotations;
using ValidationSample.Attributes;

namespace ValidationSample.Models
{
    #region snippet_ModelClass
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [ClassicMovie(1960)]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [Required]
        [StringLength(1000)]
        public string Description { get; set; }

        [Range(0, 999.99)]
        public decimal Price { get; set; }

        [Required]
        public Genre Genre { get; set; }

        public bool Preorder { get; set; }
    }
    #endregion
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Models/MovieIValidatable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ValidationSample.Models
{
    #region snippet
    public class MovieIValidatable : IValidatableObject
    {
        private const int _classicYear = 1960;

        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        public DateTime ReleaseDate { get; set; }

        [Required]
        [StringLength(1000)]
        public string Description { get; set; }

        [Range(0, 999.99)]
        public decimal Price { get; set; }

        [Required]
        public Genre Genre { get; set; }

        public bool Preorder { get; set; }

        #region snippet_Validate
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Genre == Genre.Classic && ReleaseDate.Year > _classicYear)
            {
                yield return new ValidationResult(
                    $"Classic movies must have a release year earlier than {_classicYear}.",
                    new[] { "ReleaseDate" });
            }
        }
        #endregion
    }
    #endregion
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Models/User.cs
using Microsoft.AspNetCore.Mvc;

namespace ValidationSample.Models
{
    public class User
    {
        #region snippet_UserEmailProperty
        [Remote(action: "VerifyEmail", controller: "Users")]
        public string Email { get; set; }
        #endregion

        #region snippet_UserNameProperties
        [Remote(action: "VerifyName", controller: "Users", AdditionalFields = nameof(LastName))]
        public string FirstName { get; set; }
        [Remote(action: "VerifyName", controller: "Users", AdditionalFields = nameof(FirstName))]
        public string LastName { get; set; }
        #endregion

        [Remote(action: "VerifyPhone", controller: "Users")]
        public string Phone { get; set; }

        public int Age { get; set; }
    }
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Controllers/MoviesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ValidationSample.Models;
using ValidationSample.Data;

namespace ValidationSample.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _context;

        public MoviesController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Movies);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(
            string title,
            Genre genre,
            DateTime releaseDate,
            string description,
            decimal price,
            bool preorder)
        {
            var modifiedReleaseDate = releaseDate;
            if (releaseDate == null)
            {
                modifiedReleaseDate = DateTime.Today;
            }

            #region snippet_TryValidateModel
            var movie = new Movie
            {
                Title = title,
                Genre = genre,
                ReleaseDate = modifiedReleaseDate,
                Description = description,
                Price = price,
                Preorder = preorder,
            };

            TryValidateModel(movie);

            if (ModelState.IsValid)
            {
                _context.AddMovie(movie);
                _context.SaveChanges();

                return RedirectToAction(actionName: nameof(Index));
            }

            return View(movie);
            #endregion
        }
    }
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Controllers/UsersController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ValidationSample.Models;
using ValidationSample.Data;

namespace ValidationSample.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserRepository _userRepository;

        public UsersController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult CheckEmail()
        {
            return View();
        }

        #region snippet_VerifyEmail
        [AcceptVerbs("Get", "Post")]
        public IActionResult VerifyEmail(string email)
        {
            if (!_userRepository.VerifyEmail(email))
            {
                return Json($"Email {email} is already in use.");
            }

            return Json(true);
        }
        #endregion

        #region snippet_VerifyName
        [AcceptVerbs("Get", "Post")]
        public IActionResult VerifyName(string firstName, string lastName)
        {
            if (!_userRepository.VerifyName(firstName, lastName))
            {
                return Json($"A user named {firstName} {lastName} already exists.");
            }

            return Json(true);
        }
        #endregion

        public IActionResult CheckPhone()
        {
            return View();
        }

        #region snippet_VerifyPhone
        [AcceptVerbs("Get", "Post")]
        public IActionResult VerifyPhone(
            [RegularExpression(@"^\d{3}-\d{3}-\d{4}$")] string phone)
        {
            if (!ModelState.IsValid)
            {
                return Json($"Phone {phone} has an invalid format. Format: ###-###-####");
            }

            return Json(true);
        }
        #endregion

        public IActionResult CheckName()
        {
            return View();
        }

        public IActionResult CheckAge()
        {
            return View();
        }

        #region snippet_CheckAge
        [HttpPost]
        public IActionResult CheckAge(
            [BindRequired, FromQuery] int age)
        {
        #endregion
            if (!ModelState.IsValid)
            {
                ViewData["ValidationResult"] = "Validation failed.";
                ViewData["ValidationResultColorStyle"] = "red";

                return View();
            }

            ViewData["ValidationResult"] = "Validation successful.";
            ViewData["ValidationResultColorStyle"] = "green";

            return View();
        }
    }
}

aspnetcore/mvc/models/validation/samples/2.x/ValidationSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - MVC Movies</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.8.3.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">MVC Movies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Home</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="CheckEmail">Check Email</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="CheckPhone">Check Phone</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="CheckAge">Check Age</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="CheckName">Check Name</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;@DateTime.Now.Year - MVC Movies
        </div>
    </footer>

    <!-- <snippet_ScriptTag> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- </snippet_ScriptTag> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/respond/1.4.2/respond.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>